# Generated by Django 5.0.1 on 2024-03-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
